version: '3.1'

services: 
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
          - "2181:2181"
    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
        environment: 
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_HOST_NAME: localhost